language: go

go:
  - "1.11"
  - master

sudo: required

services:
  - mysql

env:
  global:
    - GO_REPO_FULLNAME="github.com/astaxie/beego"

before_install:
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE test_db;'

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('Cindy1024') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -uroot -p

install:
  - echo "install"

  - go get -v github.com/astaxie/beego
  - go get -v github.com/go-sql-driver/mysql
  # - go get github.com/qiuchenlong/quickstart
script:
  - echo "run"
  # - sh run.sh
  # - go build main.go
  - ./quickstart
