language: go

go:
  - "1.11"
  - master

sudo: required

services:
  - mysql

env:
  global:
    - GO_REPO_FULLNAME="github.com/astaxie/beego"

before_install:
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE test_db;'

before_script:
  # - mysql -uroot -p
  - echo "USE mysql;\nSELECT * FROM user;\nUPDATE user SET authentication_string=PASSWORD('Cindy1024') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - echo "install"

  - go get -v github.com/astaxie/beego
  - go get -v github.com/go-sql-driver/mysql
  # - go get github.com/qiuchenlong/quickstart
script:
  - echo "run"
  # - sh run.sh
  - echo $PWD
  - mv $GOPATH/src/github.com/qiuchenlong/quickstart $GOPATH/src/
  - echo $PWD
  - go build main.go
  # - ./quickstart
